config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  resources :userprojects do
    resources :tickets
  end

  get 'home/index'

   root 'home#index'

end

app/models/userproject.rb
class Userproject < ActiveRecord::Base
  belongs_to :user
  has_many :tickets
end

app/controllers/userprojects_controller.rb
class UserprojectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_userproject, only: [:edit, :update, :destroy]

  # GET /userprojects
  # GET /userprojects.json
  def index
    @userprojects = Userproject.all
  end

  # GET /userprojects/1
  # GET /userprojects/1.json
  def show
  end

  # GET /userprojects/new
  def new
    @userproject = Userproject.new
  end

  # GET /userprojects/1/edit
  def edit
  end

  # POST /userprojects
  # POST /userprojects.json
  def create
    @user = current_user
    @userproject = @user.userprojects.build(userproject_params)

    respond_to do |format|
      if @userproject.save
        format.html { redirect_to @userproject, notice: 'Userproject was successfully created.' }
        format.json { render :show, status: :created, location: @userproject }
      else
        format.html { render :new }
        format.json { render json: @userproject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /userprojects/1
  # PATCH/PUT /userprojects/1.json
  def update
    respond_to do |format|
      if @userproject.update(userproject_params)
        format.html { redirect_to @userproject, notice: 'Userproject was successfully updated.' }
        format.json { render :show, status: :ok, location: @userproject }
      else
        format.html { render :edit }
        format.json { render json: @userproject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /userprojects/1
  # DELETE /userprojects/1.json
  def destroy
    @userproject.destroy
    respond_to do |format|
      format.html { redirect_to userprojects_url, notice: 'Userproject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_userproject
      @userproject = Userproject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def userproject_params
      params.require(:userproject).permit(:name, :desc)
    end
end

app/helpers/userprojects_helper.rb
module UserprojectsHelper
end

app/views/userprojects/_form.html.erb
<%= form_for(@userproject) do |f| %>
  <% if @userproject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@userproject.errors.count, "error") %> prohibited this userproject from being saved:</h2>

      <ul>
      <% @userproject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_field :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/userprojects/edit.html.erb
<h1>Editing Userproject</h1>

<%= render 'form' %>

<%= link_to 'Show', @userproject %> |
<%= link_to 'Back', userprojects_path %>

app/views/userprojects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing projects</h1>
<%= link_to 'New project', new_userproject_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="10"></th>
    </tr>
  </thead>

  <tbody>
    <% @userprojects.each do |userproject| %>
      <tr>
        <td><%= userproject.name %></td>
        <%= time_ago_in_words(userproject.created_at) %> ago by <% userproject.user.name %> <% userproject.user.lastname %>
        <td><%= userproject.desc %></td>
        <td><%= link_to 'Show', userproject %></td>
        <td><%= link_to 'Edit', edit_userproject_path(userproject) %></td>
        <td><%= link_to 'Destroy', userproject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
        <td><% if userproject.tickets.any? %> </td>
        <td>Tickets</td>
        <%= render userproject.ticket %>
      </tr>
    <% end %>
    
    <p>Add ticket</p>
    <%= form_for([userproject, userproject.ticket.build]) do |f| %>
      <%= f.text_area :name %>
      <%= submit_tag "Add" %>
    <% end %>
    
  </tbody>
</table>

<br>


<% end %>

app/views/userprojects/new.html.erb
<h1>New Userproject</h1>

<%= render 'form' %>

<%= link_to 'Back', userprojects_path %>

app/views/userprojects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @userproject.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @userproject.desc %>
</p>

<%= link_to 'Edit', edit_userproject_path(@userproject) %> |
<%= link_to 'Back', userprojects_path %>